v1-jessica/ReservasRed/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from ReservasRed.users import login_controller, logout_controller
#from ReservasRed.restringido import acceso_restringido, acceso_libre
#from ReservasRed.index_controller import index
from django.shortcuts import render
from red.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_controller),
    url(r'^logout/', logout_controller),
    url(r'^index/', index),
#    url(r'^view_reservations', viewReservations),
#    url(r'^do_reservation', doReservation),
    url(r'^red/', include('red.urls')),
]

v1-jessica/red/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers, serializers, viewsets, renderers

router = routers.DefaultRouter()
router.register(r'^rest/terminals', views.TerminalViewSet)
router.register(r'^rest/network', views.NetworkViewSet)
router.register(r'^rest/booknetwork', views.BookNetworkViewSet)
router.register(r'^rest/bookterminals', views.BookTerminalViewSet)
router.register(r'^rest/users', views.UserViewSet)

urlpatterns = [
#    url(r'^terminales/reservas', views.reservas_terminales),
#    url(r'^terminales/reservar', views.reservar_terminal),
    url(r'^', include(router.urls)),
]

v1-jessica/red/models.py
# -*- coding: iso-8859-15 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


# Create your models here.


class ResourceRequest(models.Model):
    user = models.ForeignKey('auth.User')
    resource_type = models.CharField(max_length=120)
    resource_id = models.IntegerField()
    date_start = models.DateTimeField(help_text='Fecha y hora de inicio')
    date_end = models.DateTimeField(help_text='Fecha y hora de fin')
    task_description = models.CharField(help_text='Descripción de la tarea', max_length=1024)
    #configuration_parameters = models.CharField(help_text='Parámetros de configuración modificados', max_length=1024)


class ResourceRequestForm(forms.ModelForm):
    class Meta:
        model = ResourceRequest
        fields = '__all__'


class Book(models.Model):
    user = models.ForeignKey('auth.User')
    #limit = models.Q(app_label='red', model='terminal') | \
    #    models.Q(app_label='red', model='network')
    #content_type = models.ForeignKey(ContentType,
    #                                 limit_choices_to=limit,
    #                                 null=True,
    #                                 blank=True)
    #object_id = models.PositiveIntegerField()
    #content_object = GenericForeignKey('content_type', 'object_id')
    date_start = models.DateTimeField(blank=False)
    date_end = models.DateTimeField(blank=False)
    description = models.TextField()
    state = models.TextField()
    class Meta:
        abstract = True


        
#class BookForm(forms.ModelForm):
#    class Meta:
#        model = Book
#        fields = ['object_id', 'date_start', 'date_end', 'description']


class Network(models.Model):
    network_id = models.CharField(max_length=15, primary_key=True)
    #books = GenericRelation(Book)


class Terminal(models.Model):
    imei = models.CharField(max_length=15, primary_key=True)
    sim = models.CharField(max_length=20)
    model = models.CharField(max_length=50)
    #books = GenericRelation(Book)

class BookNetwork(Book):
    network = models.ForeignKey(Network, related_name='bookings')

class BookTerminal(Book):
    terminal = models.ForeignKey(Terminal, related_name='bookings')

v1-jessica/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <title>UMAHetNet: A complete LTE-WiFi testbed as a service</title>

    <!-- Include Bootstrap and AngularJS --> 
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<script src="controllers/monroe.js"></script>

    <!-- Monroe Style -->

    <style>
        #monroeSty {
            padding-top:    25px;
            padding-botton: 25px;
            padding-right:  50px;
            padding-left:   50px;
        }
    </style>
	
	
	
	<!--<title>Sistema de reservas</title>-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="{% static 'functions.js' %}"> </script>
    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <!--<link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous">
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous">
    <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>-->
    <script
            src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/jquery.datetimepicker.min.css" />
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.full.min.js"></script>

    <script type="text/javascript">
      var USER_ID_TO_USERNAME;
      var TERMINAL_IMEI_TO_MODEL;
      var TERMINAL_MODELS;
      var TERMINAL_IMEIS;
      var TERMINAL_RESERVATIONS;
      var NET_RESERVATIONS;
      var NUMBER_OF_TERMINAL_FORMS = 0;
      var USER = '{{user.id}}';
      var USER_NAME = '{{user.username}}';
      var ADMIN_USER = '{{user.is_staff}}';
      var CSRF = '{{csrf_token}}';
      
      $( document ).ready(function() {
      $.ajaxSetup({ beforeSend: function(xhr, settings) {
                                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                        xhr.setRequestHeader("X-CSRFToken", CSRF);

                                    }
                                 }
      });
      

      // process resources
      $.ajax({url:"http://127.0.0.1:8000/red/rest/users/"}).then(process_users);
      $.ajax({url:"http://127.0.0.1:8000/red/rest/terminals/"}).then(function(response){setTimeout(process_terminals(response),1000)});
      $.ajax({url:"http://127.0.0.1:8000/red/rest/network/"}).then(function(response){setTimeout(process_network(response),1000)});
      
      // load reservations
      $.ajax({url:"http://127.0.0.1:8000/red/rest/booknetwork/"}).then(function(response){setTimeout(process_network_reservations(response),2000)});
      $.ajax({url:"http://127.0.0.1:8000/red/rest/bookterminals/"}).then(function(response){setTimeout(process_terminal_reservations(response),2000)});

      // load calendar widgets 
      $(function () {$('#id_date_start').datetimepicker({format:'Y-m-d H:i'});});
      $(function () {$('#id_date_end').datetimepicker({format:'Y-m-d H:i'});});

      // bind buttons with callbacks
      $('#add_terminal_button').click(add_terminal_callback);
      $('#submit_button').click(submit_callback);

      }); 
    </script>
    
 
</head>



<body ng-controller="resourcesCtrl" id="monroeSty">

<!-- ****************************************************************** -->
    <!-- Navigation Tabs -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="pull-left" href="https://www.monroe-project.eu/">
                    <img src = "media/monroe_logo.png" height="50" hspace="10"></img>
                </a>
                <a class="pull-left" href="https://www.uma.es/">
                    <img src = "media/uma_logo.png" height="50" hspace="10"></img>
                </a>						
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="index.html" data-toggle="tooltip" title="Network reservation system">Network reservation system</a></li>
					<li><a href="login.html" data-toggle="tooltip" title="Login">Login</a></li>
                    <!--<li><a href="NewExperiment.html" data-toggle="tooltip" title="Create a new experiment">New</a></li>
                    <li class="active"><a href="Resources.html"data-toggle="tooltip" title="Show information about Monroe resources">Resources</a></li>-->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="Help.html" data-toggle="tooltip" title="Platform help"><span class="glyphicon glyphicon-question-sign"></span> Help</a></li> <!--TODO: add link to pdf -->
               </ul>	
            </div>
        </div>
    </nav>



	
	
  <!--<h1>Network reservation system</h1>-->
  <!--<h3>This system is still beta.</h3>-->
  <!-- ****************************************************************** -->
    <!-- Resources listing -->

	
<div class="row">
   <div class="col-sm-7">
   
    <div class="panel panel-info">
		<div class="panel-heading">
		
		<div id='information-pane'>
      <h2>Network reservations</h2>
      <table id='network-reservations'>
	    <tr>
            <!--if para la columna que falta (boton de aceptar que solo se muestra a los admin)-->
            <th>From</th><th>To</th><th>By</th><th>State</th><th>Delete</th>
            {% if user.is_staff %}
                <th>Accept</th>
            {% endif %}
        </tr>
      </table>

	  	    </div>
  </div>
		</div> <!-- panel-heading-->
	
	

      <div class="panel panel-info">
		<div class="panel-heading">
		<h2>Terminal reservations</h2>
      <table id='terminals-reservations'>
            <tr>
                <th>IMEI</th><th>Model</th><th>From</th><th>To</th><th>By</th><th>State</th><th>Delete</th>
                {% if user.is_staff %}
                    <th>Accept</th>
                {% endif %}
            </tr>
      </table>

		</div> <!-- panel-heading-->
	</div>
	
	</div>

  
  
     <div class="col-sm-5">
    <div class="panel panel-info">
		<div class="panel-heading">
		
		 <div id='reservation-pane'>
      <div id='network-form'>
	  
	<h2>Book reservations</h2>
	
	<table>
	  <tr><td>From</td><td><input id="id_date_start" name="date_start"></td></tr>
	  <tr><td>To</td><td><input id="id_date_end" name="date_end"></td></tr>
	  <tr><td>Description <span style="display:inline-block; width: 0.2cm;">  </span></td><td><input id="id_description" name="description"></td></tr>
	  <tr><td>Network</td><td><select id="id_network" name="network"></select></td></tr>
	  <tr><td>.</td><td><div id="whiteline"></div></td></tr>
	  <tr><td>Status</td><td><div id="id_network_reserve_status"></div></td></tr>
	</table>
	
	
      </div>

	  <div class="col-xs-12" style="height:20px;"></div>
      <div id='terminal-reservation-area'></div>
      <a class="btn btn-success btn-xs" style="width:3cm" href='#' id='add_terminal_button'>Add terminal</a>
      <a class="btn btn-success btn-xs" style="width:3cm" href='#' id='submit_button'>Do reservation</a>
    </div>
  </div>

		</div> <!-- panel-heading-->
	</div>
  </div>
  
   
</body>
</html>

v1-jessica/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <title>UMAHetNet: A complete LTE-WiFi testbed as a service - Login </title>

    <!-- Include Bootstrap and AngularJS --> 
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<script src="controllers/monroe.js"></script>

    <!-- Monroe Style -->

    <style>
        #monroeSty {
            padding-top:    25px;
            padding-botton: 25px;
            padding-right:  50px;
            padding-left:   50px;
        }
    </style>
	
    <!--<title>Login</title> -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>



<body ng-controller="resourcesCtrl" id="monroeSty">


<!-- ****************************************************************** -->
    <!-- Navigation Tabs -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="pull-left" href="https://www.monroe-project.eu/">
                    <img src = "media/monroe_logo.png" height="50" hspace="10"></img>
                </a>
                <a class="pull-left" href="https://www.uma.es/">
                    <img src = "media/uma_logo.png" height="50" hspace="10"></img>
                </a>						
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="index.html" data-toggle="tooltip" title="Network reservation system">Network reservation system</a></li>
					<li><a href="login.html" data-toggle="tooltip" title="Login">Login</a></li>
                    <!--<li><a href="NewExperiment.html" data-toggle="tooltip" title="Create a new experiment">New</a></li>
                    <li class="active"><a href="Resources.html"data-toggle="tooltip" title="Show information about Monroe resources">Resources</a></li>-->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="Help.html" data-toggle="tooltip" title="Platform help"><span class="glyphicon glyphicon-question-sign"></span> Help</a></li> <!--TODO: add link to pdf -->
               </ul>	
            </div>
        </div>
    </nav>
	




<div class="login-page">
  <div class="form">
    <form class="register-form">
      <input type="text" placeholder="name"/>
      <input type="password" placeholder="password"/>
      <input type="text" placeholder="email address"/>
      <button>create</button>
      <p class="message">Already registered? <a href="#">Sign In</a></p>
    </form>
    <form class="login-form" action="/login/" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
      <input type="text" placeholder="username" name="username"/>
      <input type="password" placeholder="password" name="password"/>
        <input type="submit" class="button" value="login">
      <p class="message">Not registered? <a href="#">Create an account</a></p>
    </form>
  </div>
</div>
</body>
</html>

v1-jessica/templates/pagina_publica.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Esta es una página de acceso público</p>
</body>
</html>

v1-jessica/templates/pagina_restringida.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Acceso restringido</title>
</head>
<body>
<p>Esta es una página de acceso restringido</p>
</body>
</html>

v1-jessica/templates/request_bad_request.html
<html>
<head>
    <title>New Reservations</title>
</head>
<body>
<p>
Bad request<br/>
</p>
</body>
</html>

v1-jessica/templates/reservation_bad_form.html
<html>
<head>
    <title>New Reservations</title>
</head>
<body>
<p>
Form is not correct<br/>
Maybe you forgot to fill some field?<br/>
</p>
<img src="https://media.giphy.com/media/26tPj9PmmKCB8Zopq/giphy-downsized-large.gif" />
</body>
</html>

v1-jessica/templates/reservation_busy.html
<html>
<head>
    <title>New Reservations</title>
</head>
<body>
<p>
The resource is busy<br/>
BEEP BEEP RICHIE!<br/>
</p>
<img src="https://media.giphy.com/media/KpaTTnVki93oc/giphy.gif" />
</body>
</html>

v1-jessica/templates/reservation_form.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <!--<link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous">
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous">
    <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>-->
    <script
            src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/jquery.datetimepicker.min.css" />
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.full.min.js"></script>

    <script type="text/javascript">
$( document ).ready(function() {
    $(function () {
        $('#id_date_start').datetimepicker({format:'m/d/Y H:i'});
    });
    $(function () {
        $('#id_date_end').datetimepicker({format:'m/d/Y H:i'});
    });
});
    </script>
    <title>New Reservations</title>
</head>
<body>
<form method='post' action='do_reservation'>
    {% csrf_token %}
    <table>
    {{forminfo}}
    </table>
    <input type="submit" value="Reservar"/>
</form>
</body>
</html>

v1-jessica/templates/reservation_successful.html
<html>
<head>
    <title>New Reservations</title>
</head>
<body>
<p>
Reservation successful<br/>
YOU ARE TOO OLD TO STOP ME!<br/>
</p>
<img src="https://media.giphy.com/media/R66wnaZe2WAvu/giphy.gif" />
</body>
</html>

v1-jessica/templates/view_reservations.html
<html>
<head>
    <title>Reservations</title>
</head>
<body>
<table>
    <tr>
        <th>Usuario</th>
        <th>Elementos de red implicados</th>
        <th>Fecha/hora de inicio</th>
        <th>Fecha/hora de fin</th>
        <th>Descripción de la tarea</th>
        <th>Parámetros de configuración modificados</th>
    </tr>
    {% for r in reservations %}
    <tr>
        <td>{{ r.user }}</td>
        <td>{{ r.elements }}</td>
        <td>{{ r.date_start }}</td>
        <td>{{ r.date_end }}</td>
        <td>{{ r.task_description }}</td>
        <td>{{ r.configuration_parameters }}</td>
    </tr>
    {% endfor %}
</table>

</body>
</html>